### ISSUE TITLE
Publish this site and podcast

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/futureofcoding.org#25]
- [x] hackernews
- [x] subreddits
- [x] send to friends via email
- [x] publish to facebook (but not mom or family)
- [ ] add to specific facebook groups?
- [x] Twitter
- [x] product hunt

**Comment by stevekrouse** [comment]
Issues to do before launch:

- [ ] Edit research recap three #27 
- [ ] Make homepage more welcoming #16 and #15

**Comment by stevekrouse** [comment]
- [ ] https://github.com/stevekrouse/futureofcoding.org/issues/9
- [ ] https://github.com/stevekrouse/futureofcoding.org/issues/5

**Comment by stevekrouse** [comment]
- [ ] share to futureprogramming slack

**Comment by yairchu** [comment]
The new r/nosyntax subreddit :)

**Comment by stevekrouse** [comment]
Good idea @yairchu! Submitted :)
